### ISSUE TITLE
Insecure sub-modules

### ISSUE THREAD

**Issue by pboomgaart** [ahmader/node-zoho#18]
Team,

Would it be possible to bump versions on the **request** module?

Thanks,

Paul.
- qs Denial-of-Service Extended Event Loop Blocking 
- Discovered in a nested dependency:node-zoho@0.0.24request@2.34.0qs@0.6.6
- qs Denial-of-Service Memory Exhaustion VIEW ADVISORY DETAILS
- Discovered in a nested dependency:node-zoho@0.0.24request@2.34.0qs@0.6.6
- Regular Expression Denial of Service VIEW ADVISORY DETAILS
- Discovered in a nested dependency:node-zoho@0.0.24request@2.34.0hawk@1.0.0

**Comment by ahmader** [comment]
@pboomgaart I am not sure if bumping *request* module will fix your problem. 

Did you try to test it with a newer version ? can you give me more details

**Comment by BelfordZ** [comment]
There are no breaking changes between latest request and the one that is currently in use. 

Make a PR bumping the version!

**Comment by ahmader** [comment]
All packages in dependencies and devDependencies are updated.
