### ISSUE TITLE
convertLead is broken after package updating

### ISSUE THREAD

**Issue by pahan35** [ahmader/node-zoho#47]
I noticed that my code stop working after package updating
![image](https://user-images.githubusercontent.com/13823215/36151939-e8e88816-10d1-11e8-90f7-69cbfc470e11.png)

![image](https://user-images.githubusercontent.com/13823215/36151999-1d82c406-10d2-11e8-8a88-5b3d6183a102.png)

**Comment by pahan35** [comment]
I found a reason. We need change **assignTo** value to `''`

**Comment by ahmader** [comment]
Yeah seems the defaults was there and never been used before.

After fixing the unused vars using eslint this problem appeared.
