### ISSUE TITLE
Ideas for implementing download[File/Photo]

### ISSUE THREAD

**Issue by pahan35** [ahmader/node-zoho#49]
At this moment when I try execute **downloadFile** method via package I see that it happens error on **response** parsing stage because response tries to parse file body as XML and this caused error.

![image](https://user-images.githubusercontent.com/13823215/36173740-aebe6f34-1112-11e8-9ca3-7a17760b5896.png)

We've got content-type header in response and it is different than **application/xml**.

The correct expected result from this method is origin response body and parsed Content-Disposition header which easily can be done with [this package](https://www.npmjs.com/package/content-disposition)

What do you think about the way of implementing this method?

**Comment by ahmader** [comment]
@pahan35  Check #53
I have implemented `downloadFile` method. Also the tests pass for `uploadFile`, `downloadFile` and `deleteFile`.
I did not put it on master yet, tell me if it works with you?

**Comment by pahan35** [comment]
@ahmader yes. This method works pretty well.

Thanks for your work.
